/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx631                                  */
/*      FILE         :  rx631.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <stdbool.h>

#include "iodefine.h"
#include "specific_instructions.h"

#include "mrubyc.h"

#include "xprintf.h"

#define	SZ 256

int hal_write(int fd, const void * buf, int nbytes)
{
	return 0;
}

int hal_flush(int fd)
{
	return 0;
}

#define SERIAL_BUFFER_SIZE	64
uint8_t _tx_buffer[SERIAL_BUFFER_SIZE];
uint32_t _tx_buffer_head;
uint32_t _tx_buffer_tail;

unsigned char _extract_char()
{
    unsigned char c = _tx_buffer[_tx_buffer_tail];
    if (_tx_buffer_head != _tx_buffer_tail) {
      _tx_buffer_tail = (_tx_buffer_tail + 1) % SERIAL_BUFFER_SIZE;
    }
    return c;
}
bool _buffer_available()
{
    return (_tx_buffer_head != _tx_buffer_tail);
}

int gchar()
{
	uint8_t ch;

	USBCDC_GetChar(&ch);

	return(ch);
}

void pchar(unsigned char);
void pchar(unsigned char ch)
{
//	USBCDC_PutChar(ch);
	USB0.INTENB0.BIT.BRDYE = 0;
	_tx_buffer[_tx_buffer_head] = ch;
	_tx_buffer_head = (_tx_buffer_head + 1) % SERIAL_BUFFER_SIZE;
	USB0.INTENB0.BIT.BRDYE = 1;
	USB0.BRDYENB.BIT.PIPE2BRDYE = 1;
}

void c_sci5_init (mrb_vm * vm, mrb_value * v)
{
}

void c_sci5_read(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch;

	ch = gchar();
	SET_INT_RETURN(ch);
}

void c_sci5_write(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch = GET_INT_ARG(1);

	pchar(ch);
}

int main(void) {

	_tx_buffer_head = 0;
	_tx_buffer_tail = 0;


	USBCDC_Init();

	while(false == USBCDC_IsConnected()) ;

	xfunc_out=pchar;

	InitTimer();

	// dorp 2 byte ?
	xprintf("  start on RX631\r\n");

	PORTA.PDR.BIT.B0 = 1;
	PORTA.PODR.BIT.B0 = 1;

	mon();

	return 0;
}
