/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx631                                  */
/*      FILE         :  rx631.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <stdbool.h>

#include "iodefine.h"
#include "specific_instructions.h"

#include "mrubyc.h"

#include "xprintf.h"

#define	SZ 256

int hal_write(int fd, const void * buf, int nbytes)
{
	return 0;
}

int hal_flush(int fd)
{
	return 0;
}

int gchar()
{
	uint8_t ch;

	USBCDC_GetChar(&ch);

	return(ch);
}

void pchar(unsigned char);
void pchar(unsigned char ch)
{
	USBCDC_PutChar(ch);
}

void c_sci5_init (mrb_vm * vm, mrb_value * v)
{
}

void c_sci5_read(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch;

	ch = gchar();
	SET_INT_RETURN(ch);
}

void c_sci5_write(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch = GET_INT_ARG(1);

	pchar(ch);
}

int main(void) {

	USBCDC_Init();

	while(false == USBCDC_IsConnected()) ;

	xfunc_out=pchar;

	InitTimer();

	// dorp 2 byte ?
	xprintf("  start on RX631\r\n");

	PORTA.PDR.BIT.B0 = 1;
	PORTA.PODR.BIT.B0 = 1;

	mon();

	return 0;
}
