/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx631                                  */
/*      FILE         :  rx631.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <stdbool.h>

#include "iodefine.h"
#include "specific_instructions.h"

#define	SZ 256

/********************************************************************
 *
 ********************************************************************
 */
void usbWrite(int size,unsigned char *buf)
{
	int sz;
	while(size>0) {
		sz = size;
		if(sz>63) sz=63;
		USBCDC_Write(sz,buf);
		buf  += sz;
		size -= sz;
	}
}
/********************************************************************
 *
 ********************************************************************
 */

void	loop(void)
{
	unsigned char  		  buf[SZ]; 
	unsigned long size;
	while(1) {
		size=0;
		USBCDC_Read(SZ,buf,&size);
		usbWrite(size,buf);
	}
}

int main(void) {

	USBCDC_Init();

	PORTA.PDR.BIT.B0 = 1;
	PORTA.PODR.BIT.B0 = 1;

	loop();

return 0;
}
