/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  rx631                                  */
/*      FILE         :  rx631.c                                */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include <stdbool.h>

#include "iodefine.h"
#include "specific_instructions.h"

#include "mrubyc.h"

#define	SZ 256

int hal_write(int fd, const void * buf, int nbytes)
{
	return 0;
}

int hal_flush(int fd)
{
	return 0;
}

int gchar()
{
	uint8_t ch;
	int size;

	do {
		USBCDC_Read(1, &ch, &size);
	} while (size == 0);

	return(ch);
}

void pchar(unsigned char);
void pchar(unsigned char ch)
{
	USBCDC_Write(1, &ch);
}

static void c_cdc_init (mrb_vm * vm, mrb_value * v)
{
}

static void c_cdc_read(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch;

	ch = gchar();
	SET_INT_RETURN(ch);
}

static void c_cdc_write(mrb_vm * vm, mrb_value * v)
{
	uint8_t ch = GET_INT_ARG(1);

	pchar(ch);
}

/********************************************************************
 *
 ********************************************************************
 */
void usbWrite(int size,unsigned char *buf)
{
	int sz;
	while(size>0) {
		sz = size;
		if(sz>63) sz=63;
		USBCDC_Write(sz,buf);
		buf  += sz;
		size -= sz;
	}
}
/********************************************************************
 *
 ********************************************************************
 */

void	loop(void)
{
	unsigned char  		  buf[SZ]; 
	unsigned long size;
	while(1) {
		size=0;
		USBCDC_Read(SZ,buf,&size);
		usbWrite(size,buf);
	}
}

int main(void) {

	USBCDC_Init();

	PORTA.PDR.BIT.B0 = 1;
	PORTA.PODR.BIT.B0 = 1;

	loop();

return 0;
}
